### ISSUE TITLE
不保留活动的时候，无法callback

### ISSUE THREAD

**Issue by fengfengfeng1234** [DylanCaiCoding/ActivityResultLauncher#2]
打开不保留活动，就可复现

**Comment by DylanCaiCoding** [comment]
感谢反馈，之前忽略这个问题了。不过都 1202 年了，应该很少有手机会在短暂的操作后把前一个 Activity 杀了重启吧。我发现现在一般会把 minSdkVersion 设置为 21 或 23 了，可能都很难找到低端手机直接复现出来，除非是特意进入开发者模式开启不保留活动选项。

回到这个问题，个人目前想到的解决思路是自行缓存 callback，在页面销毁后能取出来回调，我迟点完善一下。

**Comment by zhaoxiuyu** [comment]
FileProvider 冲突了 @DylanCaiCoding

**Comment by fengfengfeng1234** [comment]
@DylanCaiCoding 
参考官方链接摘抄的文本：_使用相机等内存密集型操作，几乎可以确定会出现这种情况_
https://developer.android.com/training/basics/intents/result?hl=zh-cn
谢谢你的回复

**Comment by DylanCaiCoding** [comment]
> FileProvider 冲突了 @DylanCaiCoding

感谢反馈，在自己的 `FileProvider` 加上 `tools:replace="android:authorities"` 和 `tools:replace="android:resource"` 可以覆盖本库的 `FileProvider`。比如：

```xml
<provider
  android:name="androidx.core.content.FileProvider"
  android:authorities="${applicationId}.fileProvider"
  android:exported="false"
  android:grantUriPermissions="true"
  tools:replace="android:authorities">
  <meta-data
    android:name="android.support.FILE_PROVIDER_PATHS"
    android:resource="@xml/filepaths"
    tools:replace="android:resource" />
</provider>
```

如果更改了 `android:authorities`，还需要进行以下配置（需要升级到 1.1.1 版本）：

```kotlin
FileProviderUtils.authority = "$packageName.fileProvider"
```

**Comment by DylanCaiCoding** [comment]
> @DylanCaiCoding
> 参考官方链接摘抄的文本：_使用相机等内存密集型操作，几乎可以确定会出现这种情况_
> https://developer.android.com/training/basics/intents/result?hl=zh-cn
> 谢谢你的回复

上周在你反馈后我做了很多尝试。有去验证是否会出现内存回收场景，找了几台低端手机开了很多应用来测试，并没有复现，不过也可能是我的测试量还不够大。还有对这个问题进行修复，前面说的缓存 callback 的方案尝试后发现有问题，重建后回调的是之前的 Activity，会有空指针异常或内存泄漏的风险。思考了很久后在 1.1.1 新版增加了 `launcher.unprocessedResult` 得到个 LiveData，在页面回收重建后会收到未处理的数据。可能只是个补救措施，个人还有另一个封装的想法，不过会大改现有的用法，而且做不到现在的那么易用。这个我还在考虑中，后续可能会再发个大版本，目前可能就先这样。

**Comment by yizems** [comment]
@zhaoxiuyu @DylanCaiCoding 针对这个问题我补充2点吧

1. 内存不足分为2种, 一个是系统内存不足, 优先杀APP, 第二个是APP 最大内存不足, 会杀部分activity 释放内存, 这两种都有可能会导致没有回调
2. 我们线上有很多这个的crash, 原先也是忽略了这种情况, 客户也忽略了, 但是监控有很多, 所以尽量还是要兼容这个方案的, 如果你们的要求高的话

我的理解是  ResultAPI 最大的有点就是解决了回调丢失的问题, 配合Saved State , 更加轻易的实现状态恢复, 流程继续, 纯个人见解, 供参考吧

**Comment by yizems** [comment]
我再提供个思路吧，不要直接使用block，使用方法名，记录下最后一次的方法名，用反射的方式实现回掉，当然，没回收的时候可以直接调用

**Comment by DylanCaiCoding** [comment]
> 我再提供个思路吧，不要直接使用block，使用方法名，记录下最后一次的方法名，用反射的方式实现回掉，当然，没回收的时候可以直接调用

感谢反馈，这个思路感觉可以，我迟点试试。之前封装的时候感觉 ActivityResult API 比较难用，所以主要在思考怎么优化用法，没有太深入去了解源码，以为和 Fragment 实现的差不多。后来查看源码意识到问题的时候，这个库已经分享出来一段时间，有一些人在用不好大改了，比较尴尬。

在我另一个 Kotlin 工具库有实现一套纯 Kotlin 用法的，用法和现在的类似，只是把 callback 的位置换回来了。

文档：https://dylancaicoding.github.io/Longan/#/usage/activityresult
源码：https://github.com/DylanCaiCoding/Longan/blob/master/longan/src/main/java/com/dylanc/longan/ActivityResult.kt、

但是本库说了兼顾 Java 用法，不好这么改。我看下能不能用你的思路完善一下。
