### ISSUE TITLE
uri返回为null？

### ISSUE THREAD

**Issue by BakerYw** [DylanCaiCoding/ActivityResultLauncher#3]
takeVideoLauncher.launchForMediaVideo { uri ->
  if (uri != null) {
    // 录像成功
  }
}

**Comment by DylanCaiCoding** [comment]
个人没遇到过，请问是什么手机？

**Comment by BakerYw** [comment]
华为手机，11版本。
大佬方便提供个微信吗，明天上班咱们交流交流⚽️



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: DylanCai ***@***.***&gt;
发送时间: 2021年9月23日 19:15
收件人: DylanCaiCoding/ActivityResultLauncher ***@***.***&gt;
抄送: 程序员非猿 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[DylanCaiCoding/ActivityResultLauncher] uri返回为null？ (#3)





 
个人没遇到过，请问是什么手机？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DylanCaiCoding** [comment]
可以，你在微信搜我完整的 GitHub 名即可，这是我微信号

**Comment by DylanCaiCoding** [comment]
微信号是 DylanCaiCoding，别加错了。加的时候备注一下。

**Comment by BakerYw** [comment]
private val Uri.size: Long
  get() = context.contentResolver.query(this, arrayOf(OpenableColumns.SIZE), null, null, null)
    ?.use {
      if (it.moveToFirst()) {
        val size = it.getLong(it.getColumnIndex(OpenableColumns.SIZE))
        if (size == 0L) {
          try {
            context.contentResolver.openFileDescriptor(this, "r")?.statSize ?: 0
          } catch (e: FileNotFoundException) {
            0
          }
        } else {
          size
        }
      } else
        0
    } ?: 0

**Comment by BakerYw** [comment]
大佬牛逼

**Comment by DylanCaiCoding** [comment]
感谢配合测试，已发布 1.1.2 版本修复在鸿蒙手机录像失败的问题。
