### ISSUE TITLE
请教一下在非Activity/Fragment 中启动，是否无法接收onActivityResult返回值

### ISSUE THREAD

**Issue by FaceAISDK** [DylanCaiCoding/ActivityResultLauncher#7]
final StartActivityLauncher startActivityLauncher = new StartActivityLauncher(UpdateAppActivity.this);

//        Uri packageURI = Uri.parse("package:" + AppUtils.getPackageName(getBaseContext()));
//        Intent intent = new Intent(Settings.ACTION_MANAGE_UNKNOWN_APP_SOURCES, packageURI);
//        startActivityLauncher.launch(intent, new ActivityResultCallback<ActivityResult>() {
//            @Override
//            public void onActivityResult(ActivityResult result) {
//                if(result.getResultCode()== Activity.RESULT_OK){
//
//                } else {
//
//                }
//            }
//        });

上面代码注释的部分如果在Activity/Fragment 中是能正常的工作的，能拿到onActivityResult 值。但是在该Activity/Fragment 
启动的下载安装线程不能接收到返回值，是因为？

**Comment by DylanCaiCoding** [comment]
抱歉，刚看到。我测了下在子线程能正常接收到返回值。

**Comment by AnyLifeZLB** [comment]
Uri packageURI = Uri.parse("package:" + AppUtils.getPackageName(getBaseContext()));  //要安装的App包名
Intent intent = new Intent(Settings.ACTION_MANAGE_UNKNOWN_APP_SOURCES, packageURI);

是这个intent 的返回值吗？
